export const movies = [
    {
      title: 'The Shawshank',
      director: 'Frank Darabont',
      year: 1994,
      genre: ['Drama ' , ' -Crime'],
      rating:  9.3,
      img: 'https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/269295/4574754/api7mu7vf__13899.1625677082.jpg?c=2',
      details: 'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the mans unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.',
      id: 1,
      boxOffice: '$73.3M',
      time: '2h 22m',
      topCast1: 'Tim Robbins',
      topCast2: 'Morgan Freeman',
      topCast3: 'Bob Gunton',
      topCast4: 'William Sadler',
      topCast5: 'Clancy Brown',
     
      topCast1Img: 'https://m.media-amazon.com/images/M/MV5BMTI1OTYxNzAxOF5BMl5BanBnXkFtZTYwNTE5ODI4._V1_FMjpg_UX1000_.jpg',
      topCast2Img: 'https://nationaltoday.com/wp-content/uploads/2022/05/77-Morgan-Freeman.jpg.webp',
      topCast3Img: 'https://m.media-amazon.com/images/M/MV5BMjUyZDQ0NjktZmM5ZS00NzcxLTliMWYtNWUxNDcyMmExZjU0XkEyXkFqcGdeQXVyMTE1MjA4NzM@._V1_.jpg',
      topCast4Img: 'https://m.media-amazon.com/images/M/MV5BMTA1NjU3NDg1MTheQTJeQWpwZ15BbWU2MDI4OTcxMw@@._V1_FMjpg_UX1000_.jpg',
      topCast5Img: 'https://m.media-amazon.com/images/M/MV5BMTUxODY3NjAzMF5BMl5BanBnXkFtZTcwMTQ5MjYwNg@@._V1_FMjpg_UX1000_.jpg',
      
      coverImg: 'https://www.slantmagazine.com/wp-content/uploads/2004/10/shawshankredemption.jpg',
    },
    {
      title: 'The Godfather',
      director: 'Francis Ford Coppola',
      year: 1972,
      genre: ['Crime', ' Drama' , ],
      rating: 9.2,
      img: 'https://cdn.shopify.com/s/files/1/1057/4964/products/The-Godfather-Part-III-Godfather-Part-3-Vintage-Movie-Poster-Original-1-Sheet-27x41.jpg?v=1666899682',
      details: 'The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughters wedding. Michael, Vitos youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Dons influence for the same, Vito refuses to do it. What follows is a clash between Vitos fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.',
      id: 2 ,
      boxOffice: '$250M',
      time: '2h 55m',
      topCast1: 'Marlon Brando',
      topCast2: 'Al Pacino',
      topCast3: 'James Caan',
      topCast4: 'Diane Keaton',
      topCast5: 'Robert Duvall',
     
      topCast1Img: 'https://m.media-amazon.com/images/M/MV5BMTg3MDYyMDE5OF5BMl5BanBnXkFtZTcwNjgyNTEzNA@@._V1_FMjpg_UX1000_.jpg',
      topCast2Img: 'https://m.media-amazon.com/images/M/MV5BMTQzMzg1ODAyNl5BMl5BanBnXkFtZTYwMjAxODQ1._V1_FMjpg_UX1000_.jpg',
      topCast3Img: 'https://m.media-amazon.com/images/M/MV5BMTI5NjkyNDQ3NV5BMl5BanBnXkFtZTcwNjY5NTQ0Mw@@._V1_FMjpg_UX1000_.jpg',
      topCast4Img: 'https://m.media-amazon.com/images/M/MV5BMTY5NDI5OTEyOF5BMl5BanBnXkFtZTgwMzU4NDI1NzM@._V1_FMjpg_UX1000_.jpg',
      topCast5Img: 'https://m.media-amazon.com/images/M/MV5BMjk1MjA2Mjc2MF5BMl5BanBnXkFtZTcwOTE4MTUwMg@@._V1_FMjpg_UX1000_.jpg',
      
      coverImg: 'https://filmschoolrejects.com/wp-content/uploads/2022/01/The-Godfather-Marlon-Brando.jpg',
    },
    {
      title: 'Cuerella',
      director: 'Craig Gillespie',
      year:2021,
      genre: ['Crime ' , ' -Drama ' ,' -Comedy'],
      boxOffice: '$233.5M',
      time: '2h 14m',
      topCast1: 'Emma Stone',
      topCast2: 'Emma Thompson',
      topCast3: 'Joel Fry',
      topCast4: 'Paul Walter Hauser',
      topCast5: 'Mark Strong',
     
      topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
      topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
      topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
      topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
      topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
      
      coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      rating: '7.3',
      img: 'https://m.media-amazon.com/images/M/MV5BOWI5YTUxOWEtZmRiZS00ZmQxLWE2NzctYTRiODA2NzE1ZjczXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg',
      details: 'Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she is built for herself in London and wonders whether she might, indeed, be destined for more after all.'
    ,  id: 3,
    },
    {
      title: 'The Dark Knight',
      director: 'Christopher Nolan',
      year: 2008,
      genre: ['Action', 'Crime', 'Drama'],
      rating: 9.0,
      img: 'https://cdn.europosters.eu/image/750/posters/batman-dark-knight-joker-i13945.jpg',
      details: 'Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as "The Joker" appears in Gotham, creating a new wave of chaos. Batmans struggle against The Joker becomes deeply personal, forcing him to confront everything he believes and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.',
       id: 4,
      boxOffice: '$233.5M',
      time: '2h 32m',
      topCast1: 'Christian Bale',
      topCast2: 'Heath Ledger',
      topCast3: 'Aaron Eckhart',
      topCast4: 'Michael Caine',
      topCast5: 'Maggie Gyllenhaal',
     
      topCast1Img: 'https://m.media-amazon.com/images/M/MV5BMTkxMzk4MjQ4MF5BMl5BanBnXkFtZTcwMzExODQxOA@@._V1_.jpg',
      topCast2Img: 'https://m.media-amazon.com/images/M/MV5BMTI2NTY0NzA4MF5BMl5BanBnXkFtZTYwMjE1MDE0._V1_FMjpg_UX1000_.jpg',
      topCast3Img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Aaron_Eckhart_%2829830286295%29_%28cropped%29.jpg/1200px-Aaron_Eckhart_%2829830286295%29_%28cropped%29.jpg',
      topCast4Img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Michael_Caine_-_Viennale_2012_a_%28cropped%29.jpg/640px-Michael_Caine_-_Viennale_2012_a_%28cropped%29.jpg',
      topCast5Img: 'https://m.media-amazon.com/images/M/MV5BMTM1MjY3NzA4NF5BMl5BanBnXkFtZTcwNzE4MjMyMw@@._V1_FMjpg_UX1000_.jpg',
      
      movieLink: "https://cmacb.beauty/watch/%D9%85%D8%B4%D8%A7%D9%87%D8%AF%D8%A9-%D9%81%D9%8A%D9%84%D9%85-the-dark-knight-2008-%D9%85%D8%AA%D8%B1%D8%AC%D9%85",
      coverImg: 'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/46c5fcd3-9081-49e1-941f-5f31abd27f98/104dafdbefa290a79dded0fa748643b51a6b1a68.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom',
    },
    {
      title: 'Fight Club',
      director: 'David Fincher',
      year: 1999,
      genre: ['Drama'],
      rating: 8.8,
      img: 'https://forumcinemaslv.blob.core.windows.net/1012/Event_9139/portrait_large/FightClub_poster.jpg',
      details: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.'
      ,  id: 5,
      boxOffice: '$233.5M',
      time: '2h 14m',
      topCast1: 'Emma Stone',
      topCast2: 'Emma Thompson',
      topCast3: 'Joel Fry',
      topCast4: 'Paul Walter Hauser',
      topCast5: 'Mark Strong',
     
      topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
      topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
      topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
      topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
      topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
      
      coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
    },
    {
      title: 'The Lord of the Rings',
      director: 'Peter Jackson',
      year: 2001,
      genre: ['Adventure', 'Fantasy'],
      rating: 8.8,
      img: 'https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
      details: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.'
      ,  id: 6,
      boxOffice: '$233.5M',
      time: '2h 14m',
      topCast1: 'Emma Stone',
      topCast2: 'Emma Thompson',
      topCast3: 'Joel Fry',
      topCast4: 'Paul Walter Hauser',
      topCast5: 'Mark Strong',
     
      topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
      topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
      topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
      topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
      topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
      
      coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
    },
    {
      title: 'Inception',
      director: 'Christopher Nolan',
      year: 2010,
      genre: ['Action', 'Adventure', 'Sci-Fi'],
      rating: 8.7,
      img: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg',
      details: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.'
     ,id: 7,
     boxOffice: '$233.5M',
     time: '2h 14m',
     topCast1: 'Emma Stone',
     topCast2: 'Emma Thompson',
     topCast3: 'Joel Fry',
     topCast4: 'Paul Walter Hauser',
     topCast5: 'Mark Strong',
    
     topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
     topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
     topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
     topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
     topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
     
     coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
    },
    {
      title: 'The Matrix',
      director: 'Lana Wachowski, Lilly Wachowski',
      year: 1999,
      genre: ['Action', 'Sci-Fi'],
      rating: 8.7,
      img: 'https://d3tvwjfge35btc.cloudfront.net/Assets/99/247/L_p0169924799.jpg',
      details: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers'
    ,  id: 8,
    boxOffice: '$233.5M',
    time: '2h 14m',
    topCast1: 'Emma Stone',
    topCast2: 'Emma Thompson',
    topCast3: 'Joel Fry',
    topCast4: 'Paul Walter Hauser',
    topCast5: 'Mark Strong',
   
    topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
    topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
    topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
    topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
    topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
    
    coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
    },
     
      {
        title: 'Interstellar',
        director: 'Christopher Nolan',
        year: 2014,
        genre: ['Adventure', 'Drama', 'Sci-Fi'],
        rating: 8.6,
        img: 'https://cdn.shopify.com/s/files/1/0969/9128/products/INST7_1_899d958b-5091-4b6b-818b-8f06a72fca05.jpg?v=1569292610',
        details: 'A team of explorers travels through a wormhole in space in an attempt to ensure humanity\'s survival.'
      ,  id: 9,
      boxOffice: '$233.5M',
      time: '2h 14m',
      topCast1: 'Emma Stone',
      topCast2: 'Emma Thompson',
      topCast3: 'Joel Fry',
      topCast4: 'Paul Walter Hauser',
      topCast5: 'Mark Strong',
     
      topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
      topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
      topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
      topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
      topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
      
      coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      },

      {
        title: 'The Departed',
        director: 'Martin Scorsese',
        year: 2006,
        genre: ['Crime', 'Drama', 'Thriller'],
        rating: 8.5,
        img: 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg',
        details: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.'
       , id: 10,
       boxOffice: '$233.5M',
       time: '2h 14m',
       topCast1: 'Emma Stone',
       topCast2: 'Emma Thompson',
       topCast3: 'Joel Fry',
       topCast4: 'Paul Walter Hauser',
       topCast5: 'Mark Strong',
      
       topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
       topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
       topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
       topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
       topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
       
       coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      },
      {
        title: 'The Avengers',
        director: 'Joss Whedon',
        year: 2012,
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        rating: 8.0,
        img: 'https://cdn.shopify.com/s/files/1/0057/3728/3618/products/108b520c55e3c9760f77a06110d6a73b_480x.progressive.jpg?v=1573652543',
        details: 'Earth\'s mightiest heroes must come together and learn to fight as a team to stop a mischievous Loki and his alien army from enslaving humanity.'
        , id: 11,
        boxOffice: '$233.5M',
        time: '2h 14m',
        topCast1: 'Emma Stone',
        topCast2: 'Emma Thompson',
        topCast3: 'Joel Fry',
        topCast4: 'Paul Walter Hauser',
        topCast5: 'Mark Strong',
       
        topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
        topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
        topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
        topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
        topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
        
        coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      },
      {
        title: 'The Social Network',
        director: 'David Fincher',
        year: 2010,
        genre: ['Biography', 'Drama'],
        rating: 7.7,
        img: 'https://i.pinimg.com/736x/79/51/05/795105bdfe8bb26e8cf5e1ea088f61d1.jpg',
        details: 'Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook.'
        , id: 12,
        boxOffice: '$233.5M',
        time: '2h 14m',
        topCast1: 'Emma Stone',
        topCast2: 'Emma Thompson',
        topCast3: 'Joel Fry',
        topCast4: 'Paul Walter Hauser',
        topCast5: 'Mark Strong',
       
        topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
        topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
        topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
        topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
        topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
        
        coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      
      },
      {
        title: 'Forrest Gump',
        director: 'Robert Zemeckis',
        year: 1994,
        genre: ['Drama', 'Romance'],
        rating: 8.8,
        img: 'https://images-na.ssl-images-amazon.com/images/S/pv-target-images/707d3da8c5a899ae82416fbec4a26bef3420d95b674bb2093745eecf615a3d47._RI_TTW_.jpg',
        details: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.'
        , id: 13,
        boxOffice: '$233.5M',
        time: '2h 14m',
        topCast1: 'Emma Stone',
        topCast2: 'Emma Thompson',
        topCast3: 'Joel Fry',
        topCast4: 'Paul Walter Hauser',
        topCast5: 'Mark Strong',
       
        topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
        topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
        topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
        topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
        topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
        
        coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      },
      {
        title: 'The Lion King',
        director: 'Roger Allers, Rob Minkoff',
        year: 1994,
        genre: ['Animation', 'Adventure', 'Drama'],
        rating: 8.5,
        img: 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_.jpg',
        details: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.'
        , id: 14,
        boxOffice: '$233.5M',
        time: '2h 14m',
        topCast1: 'Emma Stone',
        topCast2: 'Emma Thompson',
        topCast3: 'Joel Fry',
        topCast4: 'Paul Walter Hauser',
        topCast5: 'Mark Strong',
       
        topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
        topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
        topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
        topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
        topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
        
        coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      },
      {
        title: 'The Dark Knight Rises',
        director: 'Christopher Nolan',
        year: 2012,
        genre: ['Action', 'Thriller'],
        rating: 8.4,
        img: 'https://i.ebayimg.com/images/g/TE4AAMXQ25pRnOxW/s-l960.jpg',
        details: 'Eight years after the Joker\'s reign of anarchy, Batman must confront the masked terrorist Bane to save Gotham City.'
        , id: 15,
        boxOffice: '$233.5M',
        time: '2h 14m',
        topCast1: 'Emma Stone',
        topCast2: 'Emma Thompson',
        topCast3: 'Joel Fry',
        topCast4: 'Paul Walter Hauser',
        topCast5: 'Mark Strong',
       
        topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
        topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
        topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
        topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
        topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
        
        coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      },
      {
        title: 'Jurassic Park',
        director: 'Steven Spielberg',
        year: 1993,
        genre: ['Adventure', 'Sci-Fi', 'Thriller'],
        rating: 8.1,
        img: 'https://cdn.shopify.com/s/files/1/0830/9575/products/Jurassic-Park-Editions-poster-florey_2048x.jpg?v=1654518755',
        details: 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park\'s cloned dinosaurs to run loose.'
        , id: 16,
        boxOffice: '$233.5M',
        time: '2h 14m',
        topCast1: 'Emma Stone',
        topCast2: 'Emma Thompson',
        topCast3: 'Joel Fry',
        topCast4: 'Paul Walter Hauser',
        topCast5: 'Mark Strong',
       
        topCast1Img: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Emma_Stone_at_Maniac_UK_premiere_%28cropped%29.jpg',
        topCast2Img: 'https://cdn.britannica.com/40/205240-050-31BB8996/Emma-Thompson-2013.jpg',
        topCast3Img: 'https://media1.popsugar-assets.com/files/thumbor/5oDQKTlePCX9n0_qXSOMv0vLB5Q/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/02/17/893/n/44498184/fb35f3af2c4fb698_GettyImages-1156807230/i/Joel-Fry-as-Jasper-Badun.jpg',
        topCast4Img: 'https://www.famousbirthdays.com/faces/hauser-paul-image.jpg',
        topCast5Img: 'https://static.tvtropes.org/pmwiki/pub/images/markstrong.jpg',
        
        coverImg: 'https://saintscroll.com/wp-content/uploads/2021/10/1623486101492154-20210531-Cruella-de-Vil-Preview-Image-1.jpg',
      }]

      export default movies;